services:
  - type: web
    name: Fontfeel
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_interface:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true